// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const logoJpg = 'assets/images/logo.jpg';
  static const restaurant2Jpg = 'assets/images/restaurant2.jpg';
  static const restaurant3Jpg = 'assets/images/restaurant3.jpg';
  static const restaurant4Jpg = 'assets/images/restaurant4.jpg';
  static const restaurantJpg = 'assets/images/restaurant.jpg';
  static const userPng = 'assets/images/user.png';
}

class AssetsSvgs {

}

